#pragma once

#include "lower.h"

enum class LowerCmp {
    eq, neq, gt, ge, lt, le,
    igt, ige, ilt, ile
};

// A single operation that can be performed inside a function block.
struct LowerInst {
    enum Kind: U8 {
        /*
         * Provided values (may still require instructions to generate on some architectures).
         */

        Arg,     // Defines a function argument (always represented as registers).
        Global,  // Loads the address of a global value.
        Fun,     // Loads the address of a static function.
        Imm,     // Loads an immediate value.

        /*
         * Generic instruction types generated by lowering from IR.
         */

        FirstInst,
        Nop = FirstInst,

        // Unary operations on a single value:
        FirstUnary,
        Set = FirstUnary,   // Copies the source into a new value: any
        Cast,               // Any type to any other type, discarding information if precision is lower.
        Bitcast,            // Any type to any other type, without changing the actual bits (aside from truncation if needed).

        FirstUnaryArith,
        Neg = FirstUnaryArith,  // Negates the source: int, float
        Not,                    // Inverts all bits in source: int
        LastUnaryArith = Not,
        LastUnary = LastUnaryArith,

        FirstBinary,

        // Arithmetic with multiple type support:
        Add = FirstBinary,  // Add:        int + int, ptr + int, float + float
        Sub,                // Subtract:   int - int, ptr - int, ptr - ptr, float - float
        Mul,                // Multiply:   int * int, float * float
        IMul,               // Signed mul: int * int
        Div,                // Divide:     int / int, float / float
        IDiv,               // Signed div: int / int
        Rem,                // Remainder:  int % int
        IRem,               // Signed rem: int % int

        // The *top* half of a product twice as wide as its operands: `mulhi a, b` at Int64 is bits
        // 64..127 of `a * b`. Every machine that has a multiply produces this half beside the low
        // one and throws it away; it is here because the reciprocal a division by a constant turns
        // into is exactly that half and nothing else - see lower_strength.h, which is the only
        // thing that builds one.
        MulHi,              // Unsigned high multiply: int * int
        IMulHi,             // Signed high multiply:   int * int

        // Bitwise integer operations (some support int - ptr operation as well):
        Shl,
        Shr,
        Sar,
        And,                // int & int, ptr & int
        Or,                 // int | int, ptr | int
        Xor,                // int ^ int, ptr ^ int

        // Comparison (supports any two of the same type):
        Cmp,
        LastBinary = Cmp,

        // Select from two values based on a condition, without branching.
        Select,

        Alloca,
        Load,
        Store,
        Copy,
        SetPattern,

        Call,

        // Control flow; must not exist in a block instruction list.
        FirstTerminator,
        Je = FirstTerminator,
        Jmp,
        Ret,
        LastTerminator = Ret,

        Phi,

        /*
         * Target-specific instructions created by transforms during code generation.
         */

        // Represents an X86 embedded address calculation, which doesn't require its own register.
        X86Address,

        // LEA, which can combine some cases of multiply-add into a single instruction.
        X86Lea,

        // A machine operation named directly rather than described - see LowerIntrinsic below.
        Intrinsic,

        // Stores one argument into the outgoing argument area, for a call whose convention passes
        // it there rather than in a register. Created by transformFunction from the convention's
        // own answer, never written by hand - see insertStackArgs in transform.cpp.
        X86PushArg,
        LastInst = X86PushArg,
    };

    explicit LowerInst(Kind kind): kind(kind) {}

    LowerPtr<LowerBlock> block = nullptr; // Block this instruction belongs to.
    LocationId source = kNullLocation;     // Reference to original source code location.
    U16 liveId = kNullLive;                // Index into liveness information.
    Kind kind;                             // Instruction type.
    U8 createdCount = 0;                   // Number of values created (embedded values packed into the same allocation after this header).
    U8 usedCount = 0;                      // Number of values used (pointers packed into the same allocation after created values).
    U8 flags = 0;                          // Type-specific content.

    Buffer<LowerValue> created() {
        auto created = (LowerValue*)(this + 1);
        return { created, createdCount };
    }

    Buffer<LowerPtr<LowerValue>> used() {
        auto created = (LowerValue*)(this + 1);
        auto used = (LowerPtr<LowerValue>*)(created + createdCount);
        return { used, usedCount };
    }
};

inline bool isCast(LowerInst* inst) {
    return inst->kind == LowerInst::Cast || inst->kind == LowerInst::Bitcast;
}

inline bool isUnary(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstUnary && inst->kind <= LowerInst::LastUnary;
}

inline bool isUnaryArith(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstUnaryArith && inst->kind <= LowerInst::LastUnaryArith;
}

inline bool isBinary(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstBinary && inst->kind <= LowerInst::LastBinary;
}

inline bool isTerminator(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstTerminator && inst->kind <= LowerInst::LastTerminator;
}

inline bool isCall(LowerInst* inst) {
    return inst->kind == LowerInst::Call;
}

inline bool isPhi(LowerInst* inst) {
    return inst->kind == LowerInst::Phi;
}

struct LowerInstSingle: LowerInst {
    LowerInstSingle(Kind kind, StringId name, LowerType type): LowerInst(kind), result(this, type, name) {
        createdCount = 1;
    }

    // Embedded values must be first after the base class.
    LowerValue result;
};

struct LowerInstGlobal: LowerInstSingle {
    LowerInstGlobal(StringId name, LowerPtr<LowerGlobal> target):
        LowerInstSingle(Global, name, LowerType::Pointer), target(target) {}

    LowerPtr<LowerGlobal> target;
};

struct LowerInstFun: LowerInstSingle {
    LowerInstFun(StringId name, LowerPtr<LowerFunction> target):
        LowerInstSingle(Fun, name, LowerType::Pointer), target(target) {}

    LowerPtr<LowerFunction> target;
};

// A value provided through a function parameter.
struct LowerArg: LowerInstSingle {
    LowerArg(StringId name, LowerType type, U8 index):
        LowerInstSingle(Arg, name, type)
    {
        flags = index;
    }

    U32 getIndex() const {
        return flags;
    }
};

// An immediate value that can be used by instructions.
struct LowerImm: LowerInstSingle {
    LowerImm(StringId name, LowerType type, U64 i):
        LowerInstSingle(Imm, name, type)
    {
        this->i = i;
    }

    LowerImm(StringId name, LowerType type, F64 f):
        LowerInstSingle(Imm, name, type)
    {
        this->f = f;
    }

    union {
        U64 i;
        F64 f;
    };
};

/*
 * Arithmetic.
 */

struct LowerInstUnary: LowerInstSingle {
    LowerInstUnary(Kind kind, StringId name, LowerType type, LowerPtr<LowerValue> from):
        LowerInstSingle(kind, name, type), from(from)
    {
        assertTrue(kind >= LowerInst::FirstUnary && kind <= LowerInst::LastUnary);
        usedCount = 1;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

struct LowerInstCast: LowerInstUnary {
    LowerInstCast(StringId name, LowerType type, LowerPtr<LowerValue> from, bool signedSource, bool signedResult):
        LowerInstUnary(Cast, name, type, from)
    {
        U8 f = 0;
        if(signedSource) f |= 1;
        if(signedResult) f |= 2;

        flags = f;
    }

    bool isSignedSource() const {
        return flags & 1;
    }

    bool isSignedResult() const {
        return flags & 2;
    }
};

struct LowerInstBinary: LowerInstSingle {
    LowerInstBinary(StringId name, LowerType type, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs, Kind kind):
        LowerInstSingle(kind, name, type), lhs(lhs), rhs(rhs)
    {
        assertTrue(kind >= LowerInst::FirstBinary && kind <= LowerInst::LastBinary);
        usedCount = 2;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs;
};

struct LowerInstCmp: LowerInstBinary {
    LowerInstCmp(StringId name, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs, LowerCmp cmp):
        LowerInstBinary(name, LowerType::Int32, lhs, rhs, Cmp)
    {
        flags = (U8)cmp;
    }

    LowerCmp getCmp() const {
        return (LowerCmp)flags;
    }

    // Rewrites the comparison in place, for a target that answers it the other way round: the x64
    // backend turns `a < b` into `b > a` because only one of the two reads correctly for a NaN.
    void setCmp(LowerCmp cmp) {
        flags = (U8)cmp;
    }
};

inline Maybe<LowerCmp> decodeOptionalCmp(U8 flags) {
    if(flags & 1) {
        return Just(LowerCmp(flags >> 1));
    } else {
        return Nothing();
    }
}

inline U8 encodeOptionalCmp(Maybe<LowerCmp> cmp) {
    return cmp ? (U8(cmp.unwrap()) << 1) | 1 : 0;
}

struct LowerInstSelect: LowerInstSingle {
    LowerInstSelect(StringId name, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs, LowerPtr<LowerValue> cmp, LowerType type):
        LowerInstSingle(Select, name, type), lhs(lhs), rhs(rhs), cmp(cmp)
    {
        usedCount = 3;
    }

    // Set if the comparison uses retained flags, rather than a register-stored comparison.
    // In this case, `cmp` is only used implicitly.
    Maybe<LowerCmp> getEmbeddedCmp() const {
        return decodeOptionalCmp(flags);
    }

    void setEmbeddedCmp(Maybe<LowerCmp> c) {
        flags = encodeOptionalCmp(c);
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs, cmp;
};

/*
 * Memory.
 */

// Allocates space on the stack.
struct LowerInstAlloca: LowerInstSingle {
    LowerInstAlloca(StringId name, LowerPtr<LowerValue> byteCount, U32 alignment):
        LowerInstSingle(Alloca, name, LowerType::Pointer), byteCount(byteCount), alignment(alignment)
    {
        usedCount = 1;
        assertTrue(alignment != 0 && (alignment & (alignment - 1)) == 0); // a power of two
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> byteCount;

    // What the allocated address has to be a multiple of. Stated by whoever knows what the memory is
    // going to hold rather than guessed from the byte count downstream: a 16-byte allocation of two
    // pointers wants 8, and a 4-byte one of a vector lane wants 16, and the size does not say which.
    // A power of two, and at least 1.
    U32 alignment;
};

inline bool isSignedLoad(U8 memFlags) {
    return memFlags & 8;
}

inline U32 getMemoryWidth(U8 memFlags) {
    return 1 << (memFlags & 7);
}

inline U8 makeMemoryFlags(U32 width, bool isSigned) {
    auto flags = width ? Math::findFirstBit(width) : 0;
    if(isSigned) flags |= 8;
    return flags;
}

// Loads a value from memory into a register.
// The source must be a pointer type.
// The target type determines the number of bytes loaded from memory.
struct LowerInstLoad: LowerInstSingle {
    LowerInstLoad(LowerPtr<LowerValue> from, StringId name, LowerType type, U32 width, bool isSigned):
        LowerInstSingle(Load, name, type), from(from)
    {
        usedCount = 1;
        flags = makeMemoryFlags(width, isSigned);
    }

    U32 getWidth() const {
        return getMemoryWidth(flags);
    }

    bool isSigned() const {
        return isSignedLoad(flags);
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

// Stores a value from a register into memory.
// The value stored into must be a pointer.
struct LowerInstStore: LowerInst {
    LowerInstStore(LowerPtr<LowerValue> to, LowerPtr<LowerValue> value, U32 width):
        LowerInst(Store), to(to), value(value)
    {
        usedCount = 2;
        flags = makeMemoryFlags(width, false);
    }

    U32 getWidth() const {
        return getMemoryWidth(flags);
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> to, value;
};

// Set on Copy/SetPattern by a target-specific transform to record which of the two available
// encodings the backend will use, so that the register constraints and the encoder cannot disagree
// about it. See selectBlockOpEncoding in codegen/x64/transform.cpp: the unrolled form works out of
// whatever registers the operands already occupy, while the rep-prefixed form demands fixed ones.
static constexpr U8 kBlockOpUnrolled = 1;

// Copies memory from the source pointer to the target pointer.
struct LowerInstCopy: LowerInst {
    LowerInstCopy(LowerPtr<LowerValue> to, LowerPtr<LowerValue> from, LowerPtr<LowerValue> count):
        LowerInst(Copy), to(to), from(from), count(count)
    {
        usedCount = 3;
    }

    bool isUnrolled() const { return (flags & kBlockOpUnrolled) != 0; }
    void setUnrolled(bool unrolled) { flags = unrolled ? kBlockOpUnrolled : U8(0); }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> to, from, count;
};

// Copies a pattern byte to the target pointer.
struct LowerInstSetPattern: LowerInst {
    LowerInstSetPattern(LowerPtr<LowerValue> to, LowerPtr<LowerValue> count, LowerPtr<LowerValue> pattern):
        LowerInst(SetPattern), to(to), count(count), pattern(pattern)
    {
        usedCount = 3;
    }

    bool isUnrolled() const { return (flags & kBlockOpUnrolled) != 0; }
    void setUnrolled(bool unrolled) { flags = unrolled ? kBlockOpUnrolled : U8(0); }

    // Used values must be first after embedded values.
    // The declaration order is what used() reports, and the printer emits used() positionally, so
    // it has to match the textual operand order the parser accepts: `setpattern to, count, pattern`.
    LowerPtr<LowerValue> to, count, pattern;
};

// Stores one argument into the outgoing argument area, for a call whose convention passes it on the
// stack rather than in a register.
//
// It exists to break the argument's lifetime. Written straight into the call's operand list, a stack
// argument would have to stay in a register from wherever it was computed all the way to the call,
// competing for registers with every other argument being computed in between - which is exactly
// where a call with more arguments than registers is under the most pressure. Storing it early ends
// its live range at the store, and only memory holds it from there on.
//
// That is also why this has to be an instruction rather than a move attached to some other one:
// liveness runs over instructions, so the store has to be visible to it to shorten anything.
//
// The result stands in for the argument in the call's operand list so that the call still names all
// of its arguments in order. It is implicit - nothing reads it, and it occupies no location.
struct LowerInstX86PushArg: LowerInstSingle {
    LowerInstX86PushArg(LowerPtr<LowerValue> arg, U32 stackOffset, LowerType type):
        LowerInstSingle(X86PushArg, StringId(), type), arg(arg), stackOffset(stackOffset)
    {
        result.flags = LowerValue::Implicit;
        usedCount = 1;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> arg;

    // Byte offset within the argument area, as the calling convention assigned it.
    U32 stackOffset;
};

/*
 * Intrinsics.
 *
 * A machine operation the program asked for by name, rather than one the lowering derived from
 * something more abstract. The instructions above all mean something a target-independent optimizer
 * could reason about; an intrinsic means "emit this operation", and what it does to the machine is
 * the target's description of it rather than anything stated here.
 *
 * So this carries an identifier and its operands, and nothing else. Everything an intrinsic needs in
 * order to be allocated and emitted - which registers it forces its operands into, what it clobbers,
 * which of its results goes where, how it is encoded - is one row of the target's intrinsic registry
 * (see codegen/x64/intrinsic.cpp). Adding one is that row plus a name here.
 *
 * The identifiers are named centrally, the way LowerCallType names conventions the lower IR does not
 * itself implement: an intrinsic is meaningless without a target, but the IR still has to be able to
 * write one down, print it and parse it back.
 */
enum class LowerIntrinsic: U16 {
    Bswap,   // reverse the byte order of an integer
    Popcnt,  // count the set bits of an integer
    Cpuid,   // query the processor's feature information
    Rdtscp,  // read the processor's timestamp counter and its id
    Rdtsc,   // read the processor's timestamp counter

    // Memory ordering. Neither reads nor writes anything itself; each one constrains where the
    // accesses around it may be moved to, which is why the IR has to be able to name them at all.
    MFence,
    LFence,
    SFence,
    Pause,   // a hint that this is a spin loop, not a barrier - see the registry

    // Cache and translation control. Each takes the address it operates on, and only that.
    Prefetch,     // fetch a line towards the processor, with no architectural effect
    PrefetchNta,  // the same, without displacing what the caches already hold
    Clflush,      // write a line back and evict it, everywhere it is held
    Invlpg,       // drop the translation of one page

    // Interrupts and processor state. The four below take nothing and answer nothing: what they do
    // is to the processor rather than to any value.
    Hlt,
    Cli,
    Sti,
    Swapgs,

    // Model-specific and extended-state registers.
    Rdmsr,
    Wrmsr,
    Xgetbv,

    // Port I/O, at the two widths a port is addressed at. The port number is a value rather than a
    // constant here; see the registry for why that is not the shorter encoding's fault.
    In8,
    In32,
    Out8,
    Out32,

    // Control registers. One intrinsic per register rather than one taking a number, because the
    // number is part of the encoding rather than an operand of it.
    ReadCr0,
    ReadCr2,
    ReadCr3,
    ReadCr4,
    WriteCr0,
    WriteCr3,
    WriteCr4,

    LastIntrinsic = WriteCr4,
};

static constexpr Size kLowerIntrinsicCount = Size(LowerIntrinsic::LastIntrinsic) + 1;

// What the IR itself knows about an intrinsic: how it is written, and how many values go in and come
// out. The arity is here rather than in the target registry because it is what the parser and the
// validator check, and both run before any target has been chosen.
struct LowerIntrinsicDesc {
    StringView name;
    U8 results;
    U8 args;
};

const LowerIntrinsicDesc& lowerIntrinsicDesc(LowerIntrinsic id);

// Looks an intrinsic up by the name it is written as, hashed as every identifier is. Nothing if
// there is no such intrinsic. This is what makes the table in lower.cpp the one statement of which
// intrinsics exist: the parser registers a handler per name from it and recovers the identifier
// through here, so adding a row makes an intrinsic writable with no line of its own anywhere.
Maybe<LowerIntrinsic> findLowerIntrinsic(StringId name);

struct LowerInstIntrinsic: LowerInst {
    LowerInstIntrinsic(LowerIntrinsic intrinsic, Size createdCount, Size usedCount):
        LowerInst(Intrinsic), intrinsic(intrinsic)
    {
        this->createdCount = createdCount;
        this->usedCount = usedCount;
    }

    LowerIntrinsic getIntrinsic() const { return intrinsic; }

    // LowerInst::used contains the operand list and LowerInst::created the results, both in the
    // order the intrinsic's description states.
    LowerIntrinsic intrinsic;
};

struct LowerInstCall: LowerInst {
    explicit LowerInstCall(Size createdCount, Size usedCount, LowerCallType callType): LowerInst(Call) {
        this->createdCount = createdCount;
        this->usedCount = usedCount;
        this->flags = (U8)callType;
    }

    LowerCallType getCallType() const {
        return (LowerCallType)flags;
    }

    // LowerInst::used contains the argument list. The first value is the called function.
    // LowerInst::created contains the returned values.
};

/*
 * Control flow.
 */

// Conditional branch to one of two blocks.
// Can only exist in the terminator field of a block.
struct LowerInstJe: LowerInst {
    LowerInstJe(LowerPtr<LowerValue> cond, LowerPtr<LowerBlock> then, LowerPtr<LowerBlock> otherwise):
        LowerInst(Je), then(then), otherwise(otherwise), cond(cond)
    {
        usedCount = 1;
    }

    // Set if the comparison uses retained flags, rather than a register-stored comparison.
    // In this case, `cond` is only used implicitly.
    Maybe<LowerCmp> getEmbeddedCmp() const {
        return decodeOptionalCmp(flags);
    }

    void setEmbeddedCmp(Maybe<LowerCmp> cmp) {
        flags = encodeOptionalCmp(cmp);
    }

    // Whether either edge carries a claim about how likely it is, as against both being unknown.
    bool hasLikelihood() const {
        return likelihood[0].source != LikelihoodSource::Unknown
            || likelihood[1].source != LikelihoodSource::Unknown;
    }

    LowerPtr<LowerValue> cond;
    LowerPtr<LowerBlock> then;
    LowerPtr<LowerBlock> otherwise;

    // How likely each edge is relative to the other - see EdgeLikelihood. Index 0 is `then` and
    // index 1 is `otherwise`, which is also the order the containing block lists them in
    // `outgoing`, so the two are indexed alike everywhere.
    //
    // Indexed by edge rather than named per target block, which is what makes the metadata survive
    // a CFG transform for free: splitting an edge retargets `then` or `otherwise` in place, and the
    // weight of edge 0 is still the weight of edge 0 when it now leads to the split block instead.
    // The inserted block's own jump has one successor and so needs no weight at all.
    EdgeLikelihood likelihood[2];
};

// Unconditional branch to a different block.
// Can only exist in the terminator field of a block.
struct LowerInstJmp: LowerInst {
    LowerInstJmp(LowerPtr<LowerBlock> then): LowerInst(Jmp), then(then) {}

    LowerPtr<LowerBlock> then;
};

// Return the provided value to the parent function.
// Can only exist in the terminator field of a block.
struct LowerInstRet: LowerInst {
    explicit LowerInstRet(): LowerInst(Ret) {}

    // LowerInst::usedValues contains the returned values list.
    // The list can be empty if the function returns nothing.
};

// SSA ϕ-node. Can only exist in the list of phi nodes of a block.
struct LowerInstPhi: LowerInstSingle {
    LowerInstPhi(StringId name, LowerType type): LowerInstSingle(Phi, name, type) {}

    // Returns a list of source blocks where each block corresponds to a value in LowerInst::used().
    Buffer<LowerPtr<LowerBlock>> sources() {
        auto u = used();
        return { (LowerPtr<LowerBlock>*)(u.ptr + u.length), u.length };
    }

    // LowerInst::used contains the values to pick from.
    // The list of corresponding blocks is located past the used values list.
};

inline LiveSet* Liveness::getBlock(LowerBlock* b) {
    return &blockMap[b->index];
}

inline LowerValue* Liveness::getValue(LiveId id) {
    assertTrue(id < kNullLive);
    return valueMap[id];
}

inline LiveId LowerValue::liveId() {
    auto i = inst();
    auto first = i->liveId;
    if(first == kNullLive) return kNullLive;

    return first + (this - i->created().ptr);
}
