#pragma once

#include "lower.h"

enum class LowerCmp {
    eq, neq, gt, ge, lt, le,
    igt, ige, ilt, ile,

    /*
     * "either operand is a NaN", which is not one of the six and cannot be built out of them.
     *
     * Every ordered comparison of a NaN is false, so no pair of them separates a NaN from a value
     * below the range: both answer false to `x >= lo`. That is exactly the question a saturating
     * float-to-integer conversion has to ask, since one of the two wants zero and the other wants
     * the minimum - see `saturationRange` and expandFloatToSigned.
     *
     * Float operands only. It is one condition code on x86 (parity) and `fcmp uno` on LLVM, so it is
     * cheaper on both than the equality it replaces, which needs two flags and a correction.
     *
     * `ord` is its negation and exists only to be one: nothing produces an ordered test directly,
     * and `negateCmp` has to have an answer for every code it is handed.
     */
    uno, ord
};

/*
 * The relation that holds exactly where this one does not.
 *
 * Total over the twelve, which is what makes it usable as an answer rather than as a rewrite that
 * may decline: `ord` exists so that `uno` has one, and the signed and unsigned families negate
 * within themselves - `!(a <s b)` is `a >=s b` and says nothing about the unsigned order.
 *
 * A fact about the relations rather than about any one target, so it lives here: the x64 encoder
 * negates a branch it emits the other way round, and the backend's own mask folding negates a
 * comparison it is about to complement the result of.
 */
inline LowerCmp negatedCmp(LowerCmp cmp) {
    switch(cmp) {
        case LowerCmp::eq:  return LowerCmp::neq;
        case LowerCmp::neq: return LowerCmp::eq;
        case LowerCmp::gt:  return LowerCmp::le;
        case LowerCmp::ge:  return LowerCmp::lt;
        case LowerCmp::lt:  return LowerCmp::ge;
        case LowerCmp::le:  return LowerCmp::gt;
        case LowerCmp::igt: return LowerCmp::ile;
        case LowerCmp::ige: return LowerCmp::ilt;
        case LowerCmp::ilt: return LowerCmp::ige;
        case LowerCmp::ile: return LowerCmp::igt;
        case LowerCmp::uno: return LowerCmp::ord;
        case LowerCmp::ord: return LowerCmp::uno;
    }

    return cmp;
}

// A single operation that can be performed inside a function block.
struct LowerInst {
    enum Kind: U8 {
        /*
         * Provided values (may still require instructions to generate on some architectures).
         */

        Arg,     // Defines a function argument (always represented as registers).
        Global,  // Loads the address of a global value.
        Fun,     // Loads the address of a static function.
        Imm,     // Loads an immediate value.

        /*
         * Generic instruction types generated by lowering from IR.
         */

        FirstInst,
        Nop = FirstInst,

        // Unary operations on a single value:
        FirstUnary,
        Set = FirstUnary,   // Copies the source into a new value: any
        Cast,               // Any type to any other type, discarding information if precision is lower.
        Bitcast,            // Any type to any other type, without changing the actual bits (aside from truncation if needed).

        FirstUnaryArith,
        Neg = FirstUnaryArith,  // Negates the source: int, float
        Not,                    // Inverts all bits in source: int

        /*
         * The bytes of an integer in the opposite order - `bswap`, `rev`, `llvm.bswap`.
         *
         * A kind rather than the shift-and-mask tree it can be built from, and a *unary arithmetic*
         * one rather than an intrinsic. Both halves of that matter. `LowerIntrinsic` means "emit
         * this operation" and is opaque to everything above the encoder - `writesStorage` in
         * lower_licm.cpp answers yes to every intrinsic, so a byte swap written as one would be
         * pinned inside the loop that reads a binary format, which is the only loop that has any.
         * As a unary it is repeatable, hoistable and CSE-able for nothing, `isUnary` being what
         * every pass asks.
         *
         * **Int32 or Int64, and nothing narrower.** This IR has no 16-bit scalar, so `Bswap` is
         * always the whole of its register: the 16-bit swap a program can write is expanded above
         * this seam (see `Value::ByteSwap` in resolve/inst.def and its arm in lower_calc.cpp), and
         * a backend never has to ask how much of the register the answer is.
         */
        Bswap,

        // The square root of a float or of every lane of a vector of them. One kind rather than a
        // vector one and a scalar one, for the reason the arithmetic above is one kind: what differs
        // is the operand's type and nothing else.
        Sqrt,

        /*
         * The magnitude of every lane - `andps` against a sign mask, `pabsd`, `llvm.fabs`,
         * `Math.abs`.
         *
         * A kind rather than the comparison and the select it can be built from, and the reason is a
         * *semantic* one rather than a count: every machine instruction that computes a magnitude
         * clears the sign of a NaN and the expansion preserves it, so a target using its own
         * instruction and a target expanding the shape answered differently. `Value::Abs` in the
         * resolve IR is where the language rules on that (the sign of a NaN is unspecified); this is
         * the same instruction one tier down, and every backend implements it directly.
         *
         * A float lane or a *signed* integer one, the resolver having refused the rest.
         */
        Abs,

        /*
         * The two roundings to an integral value - `roundsd`/`roundpd`, `llvm.trunc`/`llvm.round`,
         * `Math.trunc`/`Math.round`.
         *
         * Kinds for `Sqrt`'s reason and not `Abs`'s: the expansions exist and are simply not what
         * any target does. What makes them two kinds rather than one with a mode is that their tie
         * rules are decided differently and only one of them is free. `Trunc` is toward zero and
         * every target spells it in one instruction; `Round` is to nearest with ties **away from
         * zero**, which SSE4.1 has no encoding for - `roundsd` imm 0 is ties-to-even - so the x64
         * backend expands it while LLVM and JS name it directly.
         *
         * A float lane only. Rounding an integer is the identity and the resolver refuses it.
         */
        Trunc,
        Floor,
        Ceil,
        Round,
        LastUnaryArith = Round,
        LastUnary = LastUnaryArith,

        FirstBinary,

        // Arithmetic with multiple type support:
        Add = FirstBinary,  // Add:        int + int, ptr + int, float + float
        Sub,                // Subtract:   int - int, ptr - int, ptr - ptr, float - float
        Mul,                // Multiply:   int * int, float * float
        IMul,               // Signed mul: int * int
        Div,                // Divide:     int / int, float / float
        IDiv,               // Signed div: int / int
        Rem,                // Remainder:  int % int
        IRem,               // Signed rem: int % int

        // The *top* half of a product twice as wide as its operands: `mulhi a, b` at Int64 is bits
        // 64..127 of `a * b`. Every machine that has a multiply produces this half beside the low
        // one and throws it away; it is here because the reciprocal a division by a constant turns
        // into is exactly that half and nothing else - see lower_strength.h, which is the only
        // thing that builds one.
        MulHi,              // Unsigned high multiply: int * int
        IMulHi,             // Signed high multiply:   int * int

        // Bitwise integer operations (some support int - ptr operation as well):
        Shl,
        Shr,
        Sar,

        /*
         * The two rotations, which are the shifts' shape and not their semantics: nothing leaves the
         * value, and what falls off one end comes back at the other.
         *
         * **The count is taken modulo the operand's width**, which is the one thing about a rotation
         * that has to be said here rather than left to a target. It is what x86's `rol`/`ror` do -
         * the count register is masked to 5 or 6 bits, and for these two that mask *is* the modulus -
         * and it is what `llvm.fshl`/`llvm.fshr` are defined as. A rotation by the width is therefore
         * the identity rather than zero, which is where it parts company with `Shl` beside it.
         *
         * Placed immediately after `Sar` because `selectForm` indexes its shift table by the
         * distance from `Shl`; the two are the same group-2 encodings at two more opcode extensions.
         *
         * An integer or a vector of integers, on the same terms the shifts are - and a vector one is
         * a rotation *per lane*, which x86 has only at AVX-512 (`vprold`). `expandVectorRotate` is
         * the pair of shifts and an `or` everywhere else, and it is a backend's expansion rather than
         * this IR's because a target that has the instruction should reach it.
         */
        Rol,
        Ror,
        And,                // int & int, ptr & int
        Or,                 // int | int, ptr | int
        Xor,                // int ^ int, ptr ^ int

        /*
         * The three bit operations that are one instruction on a machine with BMI2 and a sequence
         * everywhere else - `Core.Bits.bitsUpTo` and `Core.BitPermute`. See the notes in
         * resolve/inst.def, which is where each one's contract is argued.
         *
         * `BitsUpTo` keeps the low `rhs` bits of `lhs` and clears the rest. **The count is read as
         * an unsigned number and saturates at the type's width**, which is the ruling and is *not*
         * `bzhi`'s own rule: that instruction reads its count from a byte, so a count of 256 is a
         * count of zero to it and is a count of "all of them" here. Whoever selects a `bzhi` owes it
         * the difference - see `expandBitsUpTo` in the x64 backend, which is where it is paid.
         *
         * `GatherBits` packs the bits of `lhs` at the set positions of `rhs` down into a contiguous
         * low field; `ScatterBits` spreads a low field back out into those positions. Total, with no
         * degenerate case to state.
         *
         * Real kinds rather than intrinsics, for `Bswap`'s reason: an intrinsic is opaque to folding,
         * to CSE and to `lower_licm.cpp` (whose `writesStorage` answers true for every one of them),
         * so a permutation against a loop-invariant mask written as one would be pinned inside the
         * loop that reads it. As binaries in the range above they are hoistable and CSE-able for
         * nothing, `isBinary` being what every pass asks.
         *
         * Placed after `Xor` and before `Cmp` deliberately: `selectForm` in the x64 backend indexes
         * its shift table by the distance from `Shl`, so nothing may be inserted between `Shl` and
         * `Ror`.
         */
        BitsUpTo,
        GatherBits,
        ScatterBits,

        /*
         * The CRC-32C step - `X86.crc32`, and the one binary here that is a named function
         * rather than an operation on bits.
         *
         * `lhs` is the running remainder and `rhs` is the chunk folded into it, both at the
         * instruction's own width, and the answer is the new remainder in the low thirty-two bits.
         * The polynomial is Castagnoli's and is not a parameter - see resolve/inst.def, where that
         * is argued, and `lib/Digest/Crc.yana`, where the IEEE one it is *not* lives.
         *
         * A real kind rather than an intrinsic, on `BitsUpTo`'s terms: a checksum over a
         * loop-invariant word written as an intrinsic would be pinned inside the loop that reads it,
         * where as a binary in this range it hoists and CSEs for nothing.
         *
         * **No backend has to expand it, and no backend other than x86-64 may see it.** SSE4.2 is
         * inside x86-64-v2 and v2 is the floor, so the one target this reaches always has the
         * instruction; a target that does not is one `X86.crc32` is not declared on, which is where
         * the choice is made rather than here.
         */
        Crc32,

        // Comparison (supports any two of the same type):
        Cmp,
        LastBinary = Cmp,

        // Select from two values based on a condition, without branching.
        Select,

        // `a * b + c`, at most once rounded. Not a Binary and not a Unary, and the one three-operand
        // arithmetic kind in this IR - see LowerInstFma.
        Fma,

        /*
         * The SHA extension's seven instructions, as two kinds - see resolve/inst.def, where what
         * each computes is argued.
         *
         * **Deliberately not in the binary range above**, and `ShaBinary` is the reason: it carries
         * an op in `flags` and there are nine of them, so a pass that read it as an ordinary binary
         * would treat `sha256msg1 a, b` and `sha1msg2 a, b` as one computation. `Cmp` sits in that
         * range with a field for exactly this reason and gets away with it because every pass that
         * handles a comparison handles it by name; nothing here should have to remember that.
         *
         * Neither has an expansion anywhere. There is no sequence of ordinary instructions that
         * stands for one of these - what stands for them is a different implementation of the same
         * digest, which the library chooses in source through `hasShaExtension`.
         */
        ShaBinary,
        Sha256Rounds,

        /*
         * `vzeroupper` - the vector state reset, written in source as `X86.vzeroupper()`.
         *
         * No operands and no result: what it changes is processor state nothing in this IR names.
         * See `Value::VZeroUpper` in resolve/inst.def for why it is a call a program writes rather
         * than something the backend inserts at the entry of a `legacyVectors` function.
         *
         * It has no expansion, on the SHA instructions' terms and for a different reason: there is
         * nothing for a target without AVX to do, so a build below that level drops it rather than
         * standing anything in for it.
         */
        VZeroUpper,

        /*
         * The five vector operations that are not one of the above.
         *
         * Everything else a vector does is an instruction that already exists: an add of two
         * vectors is an `Add`, a comparison is a `Cmp` whose result is a mask, a lane-wise select
         * is a `Select` whose condition is one, and a lane-count-preserving conversion is a `Cast`
         * whose result type says what happened. That is most of the operation set, and it is free -
         * folding, CSE, forwarding and the verifier key on the kind, and an InstBinary over a
         * vector is an InstBinary. See §3.1 of Implementation-Vector.md.
         *
         * The lane index and the shuffle pattern are *fields* rather than operands. Whoever
         * produced the IR has already rejected a runtime index (Design-Vector §3.3), so nothing
         * below here has to handle the dynamic case and nothing has to prove an index constant.
         */
        FirstVector,
        VecSplat = FirstVector, // every lane the same scalar
        VecLane,                // one lane out of a vector
        VecWithLane,            // a vector with one lane replaced
        VecShuffle,             // lanes selected from two vectors by a constant pattern
        VecReduce,              // every lane combined into one scalar
        LastVector = VecReduce,

        Alloca,
        Load,
        Store,
        Copy,
        SetPattern,

        Call,

        // Control flow; must not exist in a block instruction list.
        FirstTerminator,
        Je = FirstTerminator,
        Jmp,
        Ret,

        /*
         * A block control never leaves the end of - the abort arm of a check, and nothing else
         * today. See InstUnreachable in resolve/inst.h, which is where the fact is established.
         *
         * A terminator rather than a flag on the block, for the reason `Ret` is one: what every walk
         * below here reads is the *edges*, and having none is the whole of what this says. It
         * differs from a `Ret` in exactly one thing, which is what it cost to keep spelling it as
         * one - a return has an epilogue and a `c3`, and this encodes to nothing at all.
         */
        Unreachable,
        LastTerminator = Unreachable,

        Phi,

        /*
         * Target-specific instructions created by transforms during code generation.
         */

        // Represents an X86 embedded address calculation, which doesn't require its own register.
        X86Address,

        // LEA, which can combine some cases of multiply-add into a single instruction.
        X86Lea,

        // A machine operation named directly rather than described - see LowerIntrinsic below.
        Intrinsic,

        // Stores one argument into the outgoing argument area, for a call whose convention passes
        // it there rather than in a register. Created by transformFunction from the convention's
        // own answer, never written by hand - see insertStackArgs in transform.cpp.
        X86PushArg,

        /*
         * The lane-wise minimum or maximum of two vectors - `pminsd`, `pmaxub`, `minps`.
         *
         * Backend-private for the reason `LowerReduce::Bits` is: the portable spelling of a minimum
         * is a comparison and a select (`emitMinMax` in resolve/simd.cpp), which is what every
         * target that lacks the instruction needs anyway and what LLVM's own selection folds. x86
         * has the instruction at most lane widths, so the x64 backend recognizes the pair and writes
         * this in their place - see `selectPackedMinMax` in codegen/x64/transform_constant.cpp.
         *
         * **The operand order is the machine's and is load-bearing at a float lane.** `minps a, b`
         * answers `a < b ? a : b`, which is `b` when either operand is a NaN and `b` when both are
         * zeros of opposite sign - so exchanging the operands is a different operation, and only an
         * integer lane may have them swapped (see `isCommutativeInt`). That is exactly the order
         * `select(a < b, a, b)` states, which is why the recognition is a rewrite rather than a
         * pattern with a correction after it.
         */
        X86MinMax,

        /*
         * The widening multiply of every *other* 32-bit lane into a 64-bit one - `pmuludq`, `pmuldq`.
         *
         * Backend-private on `X86MinMax`'s terms and for a reason none of the others has: this is
         * not a lane-wise operation at all. It reads the even 32-bit lanes of both operands, ignores
         * the odd ones and answers half as many lanes twice as wide, which is a shape the portable
         * IR has no way to write and no reason to - it exists because x86's only 32x32 -> 64 packed
         * product has it.
         *
         * It is what the two multiplies the machine does not have are built out of. A quadword
         * product is three of these and the shifts and adds of long multiplication
         * (`expandQuadwordMul` in codegen/x64/transform_expand.cpp); a 32-bit lane's *high* half is two,
         * one per pair of lanes. Both are the standard sequences and neither is expressible without
         * naming the instruction, a form being unable to change how many lanes its result has.
         *
         * The signedness is the instruction's own rather than the type's, exactly as `X86MinMax`'s
         * is: `pmuludq` and `pmuldq` differ in how they read the 32-bit lanes they widen, and the
         * quadword product built out of them wants the *unsigned* one for every partial product
         * regardless of how the program spelled the multiplication - the low 64 bits of a product
         * being the same bits either way.
         */
        X86MulWide,

        /*
         * A vector kept where a mask is set and zeroed where it is not - `pand`, `andps`, `pandn`.
         *
         * Backend-private for the reason `X86MinMax` above is, and arrived at from the same
         * direction: the portable spelling is `select(m, v, 0)`, which is what a target whose select
         * is one instruction wants and what LLVM folds for itself. Here a select is `OpVBlend` -
         * three instructions and a scratch register at the baseline, `pblendvb` with its mask pinned
         * to xmm0 at SSE4.1, `vpblendvb` with three register operands under VEX - and every one of
         * those is more than the single `and` that a zero arm makes it.
         *
         * **The zero arm has to go, which is why this is a rewrite and not a form.** A form chosen
         * for the select would still list the zero as an operand, so the allocator would still hold
         * a register for it across the loop and still materialize it; what makes this worth doing is
         * that the operand disappears along with the instruction that built it.
         *
         * `complemented` is which arm was the zero. `pand` is the mask kept, `pandn` computes
         * `~lhs & rhs` and is the mask *dropped* - so the two arms of a select map onto the two
         * instructions with no negation between them. The operands are stated in the machine's
         * order, `lhs` being the one the destination is tied to: `and` is commutative and takes the
         * value first, `andn` is not and takes the mask first.
         *
         * A mask lane is all-ones or all-zeros by construction, which is the whole of why this is
         * exact at a float lane as well: `v & ~0` is `v` including a NaN's payload and both zeroes,
         * and `v & 0` is `+0.0`, which is what the select's zero arm held.
         */
        X86MaskAnd,

        /*
         * A vector's lanes rearranged by an index held in another *vector* - AVX2's `vpermd` and
         * `vpermps`.
         *
         * Backend-private on `X86MaskAnd`'s terms, and for a sharper reason than either of the two
         * above it: the portable spelling is `VecShuffle`, whose pattern is part of the instruction,
         * and this is the one machine where a general pattern is not part of the instruction at all.
         * Every shuffle AVX2 has works inside each 128-bit half; the one that crosses them takes its
         * pattern out of a register, which means the pattern has to become a **value** - a pooled
         * `.rodata` load with a live range and a register of its own - before it can be an operand.
         * A form cannot do that, because a form does not create operands.
         *
         * So `lowerWideLanePermutes` is what turns the one into the other, and what arrives here is
         * a shuffle that has already had its pattern materialized. `indices` names a source lane per
         * result lane, as `VecShuffle`'s pattern does, over the **one** source: `vpermd` reads a
         * single vector, so a cross-half pattern naming both sources is refused rather than lowered.
         */
        X86Permute,

        /*
         * A memory location read, combined with a value, and written back - `add [rdi + rcx*4], edx`.
         *
         * Backend-private on the terms `X86MinMax` states, and arrived at from the other direction:
         * the portable spelling is the three instructions this replaces - a load, an operation and a
         * store - and there is nothing wrong with them anywhere except on a machine whose ALU writes
         * its result through the same r/m field it read the operand from. x86's does, at `add`,
         * `sub`, `and`, `or` and `xor`, and what that removes is not only two of the three
         * instructions: it removes the *register* the loaded value occupied, in the innermost loop
         * of every accumulating write.
         *
         * **A store rather than an operation, which is why it defines nothing.** The result is in
         * memory; there is no value here for anything below to read, and an instruction that
         * produced one would have the allocator hold a register for a number the encoding never
         * writes. `foldStoreUpdates` in codegen/x64/transform_address.cpp is what recognizes the three, and
         * the conditions it holds them to are stated there.
         *
         * The operand order is the machine's: the location is the destination and the left-hand
         * side, so a subtraction is `[m] - value` and nothing else. A commutative operation may have
         * arrived either way round and is folded from both.
         */
        X86StoreOp,

        /*
         * The sign of a narrow value put back into the whole register - `movsx`, `movsxd`.
         *
         * Backend-private on `X86StoreOp`'s terms: the portable spelling is the pair
         * `truncateToWidth` writes (resolve/lower_type.cpp), a left shift and an arithmetic right
         * shift by the same distance, and there is nothing wrong with it. LLVM folds the pair into a
         * `sext` for itself and `(x << 16) >> 16` is the idiom a JS engine recognizes, so those two
         * backends want exactly the two instructions they are given.
         *
         * x86 does not. The shifts are two-address (`tiedDef`, see `shift` in codegen/x64/machine_forms_scalar.cpp),
         * so a source with another reader needs a copy in front of them; they are six bytes and two
         * uops where `movsx` is three or four bytes and one; and they write the flags, which a
         * sign-extension standing between a comparison and its branch has no business doing.
         * `selectSignExtends` in codegen/x64/transform_peephole.cpp recognizes the pair and writes this.
         *
         * `sourceBytes` is how much of the operand is read - one, two, or four. It is the
         * instruction's own rather than the type's for the reason `X86MulWide`'s signedness is: the
         * operand arrives in a register whose `LowerType` is the register's width, and the narrow
         * width being extended from is exactly what that type no longer says. Four is `movsxd` and
         * is only ever reached at a 64-bit result, there being no 32-to-32 encoding of it.
         */
        X86Sext,

        /*
         * A load and a store that reverse the bytes on the way - `movbe`, which is x86-64-v3.
         *
         * Backend-private on `X86StoreOp`'s terms, and for the same reason: the portable spelling is
         * the pair this replaces - a `Load` and a `Bswap`, or a `Bswap` and a `Store` - and there is
         * nothing wrong with it. LLVM folds that pair into a `movbe` for itself where its target has
         * one, and JS has no memory to fold into at all, so both of those backends want exactly the
         * two instructions they were given.
         *
         * What the fold buys here is the whole point of the instruction: a value read from a binary
         * format is byte-reversed on the way out of memory, with no register holding the unreversed
         * one and no second instruction to reverse it. It is the same trade `foldLoads` makes for
         * every other operation with an r/m operand, and it needs a kind of its own only because
         * `bswap` itself has no memory form to be the twin of - the opcode is a different one.
         *
         * `getWidth` is the access, 2, 4 or 8 bytes, exactly as a `Load`'s is. There is no sign flag
         * and no narrower width: a `movbe` is the whole of its register, and a program that reversed
         * two bytes never reached this - see `Value::ByteSwap` in resolve/inst.def for where a 16-bit
         * swap is spent. `selectByteSwapMemory` in codegen/x64/transform_address.cpp is what writes
         * both of these, and the feature test is there rather than here.
         */
        X86MovbeLoad,
        X86MovbeStore,

        /*
         * `~lhs & rhs` in one instruction - `andn`, which is BMI1.
         *
         * Backend-private on `X86Sext`'s terms: the portable spelling is the two instructions this
         * replaces, a complement and an `and`, and there is nothing wrong with them. LLVM's own
         * selection folds the pair for a target that has `andn`, and JS has no complement operator
         * that is not already `^ -1`, so both of those backends want what they were given.
         *
         * What this buys on x86 is what `X86Sext` buys and one more thing. `not r/m` is two-address
         * and writes over the operand it complements, so a mask with a second reader needs a copy in
         * front of it; the pair is five or six bytes where `andn` is five and one uop; and the `and`
         * writes the flags where `andn` writes only ZF and SF, which is the difference between
         * clearing a comparison's window and leaving it open.
         *
         * **The operand order is the machine's**, which is the whole reason this is a kind and not a
         * flag on `And`: `andn` complements its VEX.vvvv operand and nothing else, so which of the
         * two was written `not` is a fact about the instruction rather than something an operand
         * order can be relied on to carry. `lhs` is the complemented one, always.
         *
         * `selectAndNot` in codegen/x64/transform_peephole.cpp is what recognizes the pair, from
         * either side of the `and` - the operation is commutative and the complement may have
         * arrived on either.
         */
        X86AndNot,

        /*
         * The lowest set bit of a word, in the three forms BMI1 has an instruction for.
         *
         * `blsr`, `blsi` and `blsmsk` are one opcode at three extensions, and each of them is an
         * `and`, a `xor` or a negation away from the operand it reads: `x & (x - 1)` clears the
         * lowest set bit, `x & -x` isolates it, and `x ^ (x - 1)` is the mask up to and including
         * it. All three are the arithmetic a loop over the set bits of a word is written out of, and
         * all three are two instructions and a live copy of `x` without them.
         *
         * Backend-private on `X86AndNot`'s terms and with the same three gains - one instruction
         * instead of two, no tie, and the flags left as ZF and CF rather than a full `and`'s worth.
         * `selectLowestBitOps` in codegen/x64/transform_peephole.cpp recognizes all three.
         *
         * A single operand, which is what makes these worth a kind of their own rather than a form:
         * the `x` the pair names twice is *one* value here, so the copy the two-address `sub` or
         * `dec` needed goes with the instruction it fed.
         */
        X86LowBit,
        LastInst = X86LowBit,
    };

    explicit LowerInst(Kind kind): kind(kind) {}

    LowerPtr<LowerBlock> block = nullptr; // Block this instruction belongs to.
    LocationId source = kNullLocation;     // Reference to original source code location.
    U16 liveId = kNullLive;                // Index into liveness information.
    Kind kind;                             // Instruction type.
    U8 createdCount = 0;                   // Number of values created (embedded values packed into the same allocation after this header).
    U8 usedCount = 0;                      // Number of values used (pointers packed into the same allocation after created values).
    U8 flags = 0;                          // Type-specific content.

    Buffer<LowerValue> created() {
        auto created = (LowerValue*)(this + 1);
        return { created, createdCount };
    }

    Buffer<LowerPtr<LowerValue>> used() {
        auto created = (LowerValue*)(this + 1);
        auto used = (LowerPtr<LowerValue>*)(created + createdCount);
        return { used, usedCount };
    }
};

inline bool isCast(LowerInst* inst) {
    return inst->kind == LowerInst::Cast || inst->kind == LowerInst::Bitcast;
}

inline bool isUnary(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstUnary && inst->kind <= LowerInst::LastUnary;
}

inline bool isUnaryArith(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstUnaryArith && inst->kind <= LowerInst::LastUnaryArith;
}

inline bool isBinary(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstBinary && inst->kind <= LowerInst::LastBinary;
}

inline bool isTerminator(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstTerminator && inst->kind <= LowerInst::LastTerminator;
}

inline bool isCall(LowerInst* inst) {
    return inst->kind == LowerInst::Call;
}

// One of the five that only a vector value can be an operand or a result of. Everything else a
// vector does is one of the instructions above, with vector operands.
inline bool isVectorInst(LowerInst* inst) {
    return inst->kind >= LowerInst::FirstVector && inst->kind <= LowerInst::LastVector;
}

inline bool isPhi(LowerInst* inst) {
    return inst->kind == LowerInst::Phi;
}

struct LowerInstSingle: LowerInst {
    LowerInstSingle(Kind kind, StringId name, LowerType type): LowerInst(kind), result(this, type, name) {
        createdCount = 1;
    }

    // Embedded values must be first after the base class.
    LowerValue result;
};

struct LowerInstGlobal: LowerInstSingle {
    LowerInstGlobal(StringId name, LowerPtr<LowerGlobal> target):
        LowerInstSingle(Global, name, LowerType::Pointer), target(target) {}

    LowerPtr<LowerGlobal> target;
};

struct LowerInstFun: LowerInstSingle {
    LowerInstFun(StringId name, LowerPtr<LowerFunction> target):
        LowerInstSingle(Fun, name, LowerType::Pointer), target(target) {}

    LowerPtr<LowerFunction> target;
};

// A value provided through a function parameter.
struct LowerArg: LowerInstSingle {
    LowerArg(StringId name, LowerType type, U8 index):
        LowerInstSingle(Arg, name, type)
    {
        flags = index;
    }

    U32 getIndex() const {
        return flags;
    }
};

// An immediate value that can be used by instructions.
struct LowerImm: LowerInstSingle {
    LowerImm(StringId name, LowerType type, U64 i):
        LowerInstSingle(Imm, name, type)
    {
        this->i = i;
    }

    LowerImm(StringId name, LowerType type, F64 f):
        LowerInstSingle(Imm, name, type)
    {
        this->f = f;
    }

    union {
        U64 i;
        F64 f;
    };
};

/*
 * Arithmetic.
 */

struct LowerInstUnary: LowerInstSingle {
    LowerInstUnary(Kind kind, StringId name, LowerType type, LowerPtr<LowerValue> from):
        LowerInstSingle(kind, name, type), from(from)
    {
        assertTrue(kind >= LowerInst::FirstUnary && kind <= LowerInst::LastUnary);
        usedCount = 1;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

struct LowerInstCast: LowerInstUnary {
    LowerInstCast(StringId name, LowerType type, LowerPtr<LowerValue> from, bool signedSource, bool signedResult):
        LowerInstUnary(Cast, name, type, from)
    {
        U8 f = 0;
        if(signedSource) f |= 1;
        if(signedResult) f |= 2;

        flags = f;
    }

    bool isSignedSource() const {
        return flags & 1;
    }

    bool isSignedResult() const {
        return flags & 2;
    }

    // Whether the source already holds the result's representation, so the extension or truncation
    // this cast describes needs no instruction of its own. Recorded by the backend rather than by
    // the lowering - what it means is a question about registers - in the same way a Copy carries
    // its chosen encoding and a Select its folded comparison. See trySkipCastExtend in the x64
    // transform, which is the only thing that sets it.
    bool skipsExtend() const {
        return flags & 4;
    }

    void setSkipsExtend(bool skips) {
        flags = U8((flags & ~4) | (skips ? 4 : 0));
    }
};

struct LowerInstBinary: LowerInstSingle {
    /*
     * Set on a division that answers a zero divisor by *trusting a test above it* rather than by
     * building the answer itself - see `divisorKnownNonZero` in lower/lower_divide.cpp.
     *
     * Every other division this compiler emits is total, which is what lets the passes below treat
     * the four dividing operations as ordinary arithmetic. One with this bit is the exception, and
     * the exception is exactly a *position*: it cannot fault where it stands, and would where the
     * test does not reach. So the only reader is the one pass that moves a computation to a point it
     * did not run at - `mayFault` in lower_licm.cpp - and the bit says "not above this branch"
     * rather than "may trap".
     *
     * Read only on Div/IDiv/Rem/IRem, where `flags` is otherwise unused: `LowerInstCmp` has the low
     * four bits and its own kind, and `LowerInstCast` is a unary.
     */
    static constexpr U8 kTrustsDivisorTest = 0x40;

    bool trustsDivisorTest() const { return (flags & kTrustsDivisorTest) != 0; }
    void setTrustsDivisorTest() { flags |= kTrustsDivisorTest; }

    LowerInstBinary(StringId name, LowerType type, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs, Kind kind):
        LowerInstSingle(kind, name, type), lhs(lhs), rhs(rhs)
    {
        assertTrue(kind >= LowerInst::FirstBinary && kind <= LowerInst::LastBinary);
        usedCount = 2;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs;
};

struct LowerInstCmp: LowerInstBinary {
    // The result type is a parameter rather than a constant because a comparison of two vectors
    // answers a mask of their shape where one of two scalars answers a Bool - which is the whole of
    // what a vector comparison changes about this instruction (§3.1 of Implementation-Vector.md).
    LowerInstCmp(StringId name, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs, LowerCmp cmp,
                 LowerType type = LowerType::Int32):
        LowerInstBinary(name, type, lhs, rhs, Cmp)
    {
        flags = (U8)cmp;
    }

    LowerCmp getCmp() const {
        return (LowerCmp)(flags & kCmpMask);
    }

    // Rewrites the comparison in place, for a target that answers it the other way round: the x64
    // backend turns `a < b` into `b > a` because only one of the two reads correctly for a NaN.
    void setCmp(LowerCmp cmp) {
        flags = U8((flags & ~kCmpMask) | (U8)cmp);
    }

    /*
     * Whether the answer to this comparison is already in the machine's flags where it stands, so
     * that it is carried rather than performed.
     *
     * `a - 1 != 0` is the shape: the subtraction set the zero flag from its own result, and the
     * comparison below it recomputes what is standing right there. Set by the x64 compare folding
     * (`tryElideCompare` in codegen/x64/transform_peephole.cpp) and read by its form selection; nothing
     * outside that backend writes it, and nothing anywhere reads it to mean anything else.
     *
     * It lives here for the same reason `LowerInstJe::setEmbeddedCmp` and `LowerValue::Implicit` do:
     * what it records is which instruction ends up producing a value, and the instructions are where
     * the backends write that down. It is deliberately *not* printed - a fold that changes no
     * operand and no edge has nothing to say in the IR text.
     */
    bool getFlagsLive() const {
        return (flags & kFlagsLive) != 0;
    }

    void setFlagsLive() {
        flags |= kFlagsLive;
    }

private:
    static constexpr U8 kCmpMask = 0x0f;   // ten comparison kinds, so four bits hold them
    static constexpr U8 kFlagsLive = 0x80;
};

inline Maybe<LowerCmp> decodeOptionalCmp(U8 flags) {
    if(flags & 1) {
        return Just(LowerCmp(flags >> 1));
    } else {
        return Nothing();
    }
}

inline U8 encodeOptionalCmp(Maybe<LowerCmp> cmp) {
    return cmp ? (U8(cmp.unwrap()) << 1) | 1 : 0;
}

struct LowerInstSelect: LowerInstSingle {
    LowerInstSelect(StringId name, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs, LowerPtr<LowerValue> cmp, LowerType type):
        LowerInstSingle(Select, name, type), lhs(lhs), rhs(rhs), cmp(cmp)
    {
        usedCount = 3;
    }

    // Set if the comparison uses retained flags, rather than a register-stored comparison.
    // In this case, `cmp` is only used implicitly.
    Maybe<LowerCmp> getEmbeddedCmp() const {
        return decodeOptionalCmp(flags);
    }

    void setEmbeddedCmp(Maybe<LowerCmp> c) {
        flags = encodeOptionalCmp(c);
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs, cmp;
};

/*
 * `a * b + c`, at most once rounded - see the kind's note above.
 *
 * Three used values and one type: all three operands and the result are the same float, or the same
 * vector of floats. There is nothing to embed and nothing optional, which is why this is a struct of
 * its own rather than a Binary with a third field bolted on.
 */
struct LowerInstFma: LowerInstSingle {
    LowerInstFma(StringId name, LowerType type, LowerPtr<LowerValue> a, LowerPtr<LowerValue> b,
                 LowerPtr<LowerValue> c):
        LowerInstSingle(Fma, name, type), a(a), b(b), c(c)
    {
        usedCount = 3;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> a, b, c;
};

/*
 * Which of the SHA extension's two-operand instructions a `ShaBinary` is.
 *
 * The same nine as `ShaOp` in resolve/inst.h and a second enum rather than that one, on
 * `LowerReduce`'s terms: the two tiers do not include each other's headers, and a seam that has to
 * translate is a seam that cannot silently drift when one side gains a member.
 */
enum class LowerSha: U8 {
    Sha1Msg1,
    Sha1Msg2,
    Sha1NextE,
    Sha1Rounds0,
    Sha1Rounds1,
    Sha1Rounds2,
    Sha1Rounds3,
    Sha256Msg1,
    Sha256Msg2,
};

// The nine as text - what the lower printer writes and what a `.lower` fixture reads back.
inline StringView nameOfLowerSha(LowerSha op) {
    switch(op) {
        case LowerSha::Sha1Msg1:    return "sha1msg1"_v;
        case LowerSha::Sha1Msg2:    return "sha1msg2"_v;
        case LowerSha::Sha1NextE:   return "sha1nexte"_v;
        case LowerSha::Sha1Rounds0: return "sha1rnds4_0"_v;
        case LowerSha::Sha1Rounds1: return "sha1rnds4_1"_v;
        case LowerSha::Sha1Rounds2: return "sha1rnds4_2"_v;
        case LowerSha::Sha1Rounds3: return "sha1rnds4_3"_v;
        case LowerSha::Sha256Msg1:  return "sha256msg1"_v;
        default:                    return "sha256msg2"_v;
    }
}

/*
 * The SHA extension's two-operand instructions - `LowerInst::ShaBinary`.
 *
 * Two used values, one type, and the instruction itself in `flags`. All three of the operands and
 * the result are a four-lane vector of 32-bit words, which the resolve verifier has already checked
 * and which is the register the machine reads.
 *
 * `flags` and not a field past the operands, which is `VecShuffle`'s mistake read the other way: a
 * value there is compared by `sameCarriedData` for nothing, so two of these that are different
 * instructions over the same pair of vectors are told apart by CSE without a case being written.
 */
struct LowerInstShaBinary: LowerInstSingle {
    LowerInstShaBinary(StringId name, LowerType type, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs,
                       LowerSha op):
        LowerInstSingle(ShaBinary, name, type), lhs(lhs), rhs(rhs)
    {
        usedCount = 2;
        flags = (U8)op;
    }

    LowerSha getSha() const { return (LowerSha)flags; }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs;
};

/*
 * `sha256rnds2` - the one SHA instruction with three operands.
 *
 * `state` is the four working words it advances, `feed` is the four it reads them against, and
 * `keys` is the message words with their round constants already added. On the machine that third
 * operand is **implicitly xmm0**, which is a constraint the x64 form carries and nothing at this
 * tier has to know: here it is an ordinary third use.
 */
struct LowerInstSha256Rounds: LowerInstSingle {
    LowerInstSha256Rounds(StringId name, LowerType type, LowerPtr<LowerValue> state,
                          LowerPtr<LowerValue> feed, LowerPtr<LowerValue> keys):
        LowerInstSingle(Sha256Rounds, name, type), state(state), feed(feed), keys(keys)
    {
        usedCount = 3;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> state, feed, keys;
};

/*
 * Vectors.
 */

/*
 * Which reduction a VecReduce performs.
 *
 * One kind with a field rather than six kinds, so that `any`, `all`, `horizontalSum` and the rest
 * are one instruction to fold, to cost and to expand. The signed pair follows the naming the binary
 * operations already use: `Min` is the unsigned or floating one and `IMin` the signed integer one,
 * exactly as `Div` and `IDiv` are.
 *
 * The order of a floating-point reduction is a stated language property rather than an
 * implementation detail - see Design-Vector §4.5 - so this says *what* is combined and the
 * expansion owes the pairwise tree that says in which order.
 */
enum class LowerReduce: U8 {
    Add,
    Mul,
    Min,
    IMin,
    Max,
    IMax,
    And,
    Or,

    /*
     * The lanes of a *mask*, as bits of an integer - lane `i` in bit `i`, and nothing above the lane
     * count.
     *
     * Not a combination at all, which is why it sits after the eight rather than among them: it is
     * the one thing a machine can do to a mask that the eight are then arithmetic on. `any` is it
     * against zero, `all` is it against the full pattern, `count` is its population and `firstSet`
     * is its lowest set bit - four answers off one instruction, where each of the four expanded on
     * its own is a reduction tree.
     *
     * **Written by a backend for itself, and never by anything above one.** `x86` has `pmovmskb` and
     * ARM does not, so a target that lacks the instruction never sees this kind rather than having
     * to expand it; the portable spelling of all four stays what `simd.cpp` emits. The validator
     * still states its rule, the printer still names it and the parser still reads it back, because
     * an IR this backend hands to its own next pass has to be one that round-trips.
     */
    Bits,

    /*
     * The lowest set lane of a mask, or the lane count where none is set.
     *
     * The portable one of the pair, and the reason `Bits` may stay private: a lane index is a thing
     * every backend can answer and no two answer alike, so what crosses this boundary is the
     * question rather than one target's way of asking it. x64 reads it off the movemask above with a
     * bit scan, LLVM bitcasts the `<N x i1>` to an integer and counts its trailing zeros, and the
     * JavaScript backend - where a lane is a variable and there is no mask to scan - emits the chain
     * of conditionals that is the same answer.
     *
     * Its result is an `Int32` and not the lane's scalar form, for the reason `Bits` is one: a mask
     * of thirty-two `i8` lanes answers 32 where nothing is set, which is not a value an `i8` holds.
     */
    FirstSet,
};

// Every lane of the result is the same scalar. The source is the lane type's scalar form - see
// scalarFormOf, which is what an 8- or 16-bit lane arrives in.
struct LowerInstVecSplat: LowerInstSingle {
    LowerInstVecSplat(StringId name, LowerType type, LowerPtr<LowerValue> from):
        LowerInstSingle(VecSplat, name, type), from(from)
    {
        usedCount = 1;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

/*
 * One lane read out of a vector, and a vector with one lane written into it.
 *
 * Two kinds sharing a struct, the way Init and Assign do above: the second is the first plus the
 * value to write, and every pass that reasons about the lane index reasons about both.
 */
struct LowerInstVecLane: LowerInstSingle {
    // `vlane v, i`: the result is the lane's scalar form.
    LowerInstVecLane(StringId name, LowerType type, LowerPtr<LowerValue> from, U8 lane):
        LowerInstSingle(VecLane, name, type), from(from), value(nullptr)
    {
        usedCount = 1;
        flags = lane;
    }

    // `vwithlane v, i, x`: the result is the vector.
    LowerInstVecLane(StringId name, LowerType type, LowerPtr<LowerValue> from, U8 lane, LowerPtr<LowerValue> value):
        LowerInstSingle(VecWithLane, name, type), from(from), value(value)
    {
        usedCount = 2;
        flags = lane;
    }

    U8 getLane() const { return flags; }

    // Used values must be first after embedded values. `value` is not one of them for a VecLane,
    // which states usedCount = 1 and leaves it null.
    LowerPtr<LowerValue> from, value;
};

/*
 * Lanes selected from two vectors by a constant pattern.
 *
 * The pattern has one entry per lane of the *result*, each naming a lane of the concatenation of the
 * two sources: `i < lanes` is a lane of the first and `i >= lanes` a lane of the second. A shuffle
 * within one vector names the same value twice, which is what every backend expects to see and what
 * keeps the pattern's meaning independent of how many sources were meant.
 *
 * The pattern is stored past the used values, the way a phi stores its source blocks: it is as long
 * as the result has lanes, so it is not a fixed field, and it belongs to the instruction's own
 * allocation rather than to a list somewhere else.
 */
struct LowerInstVecShuffle: LowerInstSingle {
    LowerInstVecShuffle(StringId name, LowerType type, LowerPtr<LowerValue> left, LowerPtr<LowerValue> right):
        LowerInstSingle(VecShuffle, name, type), left(left), right(right)
    {
        usedCount = 2;
    }

    // One entry per lane of the result. Written by whoever allocated the instruction, which has to
    // have reserved `type.lanes()` bytes past the used values for it.
    Buffer<U8> pattern() {
        auto u = used();
        auto p = (U8*)(u.ptr + u.length);

        // The pattern starts where this instruction ends, which is what the allocation reserving
        // `patternBytes` past the struct assumes. Both halves of that are stated in one place, so a
        // field added above cannot silently move the pattern into the middle of itself.
        assertTrue(p == (U8*)this + sizeof(LowerInstVecShuffle));
        return { p, result.type.lanes() };
    }

    // How much an allocation of one of these needs beyond the struct itself.
    static Size patternBytes(LowerType type) { return type.lanes(); }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> left, right;
};

// Every lane combined into one scalar, in the pairwise order Design-Vector §4.5 states. The result
// is the lane type's scalar form; for a mask it is an Int32, so `any` is Or, `all` is And and the
// number of lanes set is Add.
struct LowerInstVecReduce: LowerInstSingle {
    LowerInstVecReduce(StringId name, LowerType type, LowerPtr<LowerValue> from, LowerReduce reduce):
        LowerInstSingle(VecReduce, name, type), from(from)
    {
        usedCount = 1;
        flags = (U8)reduce;
    }

    LowerReduce getReduce() const { return (LowerReduce)flags; }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

/*
 * Memory.
 */

// Allocates space on the stack.
struct LowerInstAlloca: LowerInstSingle {
    LowerInstAlloca(StringId name, LowerPtr<LowerValue> byteCount, U32 alignment):
        LowerInstSingle(Alloca, name, LowerType::Pointer), byteCount(byteCount), alignment(alignment)
    {
        usedCount = 1;
        assertTrue(alignment != 0 && (alignment & (alignment - 1)) == 0); // a power of two
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> byteCount;

    // What the allocated address has to be a multiple of. Stated by whoever knows what the memory is
    // going to hold rather than guessed from the byte count downstream: a 16-byte allocation of two
    // pointers wants 8, and a 4-byte one of a vector lane wants 16, and the size does not say which.
    // A power of two, and at least 1.
    U32 alignment;
};

inline bool isSignedLoad(U8 memFlags) {
    return memFlags & 8;
}

/*
 * That a load reads up to a vector's width past the end of what it names, deliberately.
 *
 * A vector loop's last iteration reads a whole register where only part of it is wanted, and the
 * tail-read guarantee is what makes that safe: storage the language allocated has room after it, so
 * the bytes past the end are unspecified rather than unmapped (Design-Vector §5.4). This flag is how
 * an instruction says it is relying on that, and it is load-bearing in three places above the
 * backend - the range analysis must not keep a bounds check for it, provenance must treat it as
 * reading the place it names and nothing more, and the verifier checks that the place is rooted in
 * storage that carries the guarantee.
 *
 * Below the backend it means one further thing, which is why it is carried into the lower IR at all:
 * the legalizer must not narrow such a load, and nothing may conclude anything about the bytes it
 * read past the end.
 *
 * No store ever carries it, which is why this is on the load's flags and not in makeMemoryFlags.
 */
inline bool isOverreadLoad(U8 memFlags) {
    return memFlags & 16;
}

inline U32 getMemoryWidth(U8 memFlags) {
    return 1 << (memFlags & 7);
}

inline U8 makeMemoryFlags(U32 width, bool isSigned) {
    auto flags = width ? Math::findFirstBit(width) : 0;
    if(isSigned) flags |= 8;
    return flags;
}

// Loads a value from memory into a register.
// The source must be a pointer type.
// The target type determines the number of bytes loaded from memory.
struct LowerInstLoad: LowerInstSingle {
    LowerInstLoad(LowerPtr<LowerValue> from, StringId name, LowerType type, U32 width, bool isSigned):
        LowerInstSingle(Load, name, type), from(from)
    {
        usedCount = 1;
        flags = makeMemoryFlags(width, isSigned);
    }

    U32 getWidth() const {
        return getMemoryWidth(flags);
    }

    bool isSigned() const {
        return isSignedLoad(flags);
    }

    bool isOverread() const {
        return isOverreadLoad(flags);
    }

    void setOverread() {
        flags |= 16;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

// Stores a value from a register into memory.
// The value stored into must be a pointer.
struct LowerInstStore: LowerInst {
    LowerInstStore(LowerPtr<LowerValue> to, LowerPtr<LowerValue> value, U32 width):
        LowerInst(Store), to(to), value(value)
    {
        usedCount = 2;
        flags = makeMemoryFlags(width, false);
    }

    U32 getWidth() const {
        return getMemoryWidth(flags);
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> to, value;
};

/*
 * A location read, combined with a value and written back in place - see LowerInst::X86StoreOp.
 *
 * Written exactly as a store is, and the two differ in one field: `op` says which operation combines
 * what is there with what arrives. It is one of the five the machine can perform through its r/m
 * field - Add, Sub, And, Or, Xor - and `getWidth` is the store's width, which is the width the
 * operation is performed at as well.
 */
struct LowerInstX86StoreOp: LowerInst {
    LowerInstX86StoreOp(LowerPtr<LowerValue> to, LowerPtr<LowerValue> value, U32 width, Kind op):
        LowerInst(X86StoreOp), to(to), value(value), op(op)
    {
        usedCount = 2;
        flags = makeMemoryFlags(width, false);
    }

    U32 getWidth() const {
        return getMemoryWidth(flags);
    }

    Kind getOp() const {
        return op;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> to, value;

    // Which of the five, as the binary instruction kind it was folded out of.
    Kind op;
};

// Copies memory from the source pointer to the target pointer.
struct LowerInstCopy: LowerInst {
    LowerInstCopy(LowerPtr<LowerValue> to, LowerPtr<LowerValue> from, LowerPtr<LowerValue> count):
        LowerInst(Copy), to(to), from(from), count(count)
    {
        usedCount = 3;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> to, from, count;
};

// Copies a pattern byte to the target pointer.
// `vzeroupper` - see `LowerInst::VZeroUpper`. Nothing to carry: no operands, no result, no fields.
struct LowerInstVZeroUpper: LowerInst {
    LowerInstVZeroUpper(): LowerInst(VZeroUpper) {}
};

struct LowerInstSetPattern: LowerInst {
    LowerInstSetPattern(LowerPtr<LowerValue> to, LowerPtr<LowerValue> count, LowerPtr<LowerValue> pattern):
        LowerInst(SetPattern), to(to), count(count), pattern(pattern)
    {
        usedCount = 3;
    }

    // Used values must be first after embedded values.
    // The declaration order is what used() reports, and the printer emits used() positionally, so
    // it has to match the textual operand order the parser accepts: `setpattern to, count, pattern`.
    LowerPtr<LowerValue> to, count, pattern;
};

// Stores one argument into the outgoing argument area, for a call whose convention passes it on the
// stack rather than in a register.
//
// It exists to break the argument's lifetime. Written straight into the call's operand list, a stack
// argument would have to stay in a register from wherever it was computed all the way to the call,
// competing for registers with every other argument being computed in between - which is exactly
// where a call with more arguments than registers is under the most pressure. Storing it early ends
// its live range at the store, and only memory holds it from there on.
//
// That is also why this has to be an instruction rather than a move attached to some other one:
// liveness runs over instructions, so the store has to be visible to it to shorten anything.
//
// The result stands in for the argument in the call's operand list so that the call still names all
// of its arguments in order. It is implicit - nothing reads it, and it occupies no location.
struct LowerInstX86PushArg: LowerInstSingle {
    LowerInstX86PushArg(LowerPtr<LowerValue> arg, U32 stackOffset, LowerType type):
        LowerInstSingle(X86PushArg, StringId(), type), arg(arg), stackOffset(stackOffset)
    {
        result.flags = LowerValue::Implicit;
        usedCount = 1;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> arg;

    // Byte offset within the argument area, as the calling convention assigned it.
    U32 stackOffset;
};

/*
 * Which minimum or maximum a `X86MinMax` performs.
 *
 * The naming the binary operations and `LowerReduce` already use: `Min` is the unsigned or floating
 * one and `IMin` the signed integer one, exactly as `Div` and `IDiv` are. A float lane is `Min` -
 * there being one ordering of floats - and the signedness of an integer lane is the lane type's.
 */
enum class LowerMinMax: U8 {
    Min,
    IMin,
    Max,
    IMax,
};

// The lane-wise minimum or maximum of two vectors - see LowerInst::X86MinMax, which states why this
// is the backend's own instruction and why its operand order may not be exchanged at a float lane.
struct LowerInstX86MinMax: LowerInstSingle {
    LowerInstX86MinMax(StringId name, LowerType type, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs,
                       LowerMinMax kind):
        LowerInstSingle(X86MinMax, name, type), lhs(lhs), rhs(rhs)
    {
        usedCount = 2;
        flags = U8(kind);
    }

    LowerMinMax getMinMax() const { return (LowerMinMax)flags; }

    bool isMax() const {
        auto kind = getMinMax();
        return kind == LowerMinMax::Max || kind == LowerMinMax::IMax;
    }

    // Whether the lanes are read as signed, which for an integer lane is what picks `pminsd` over
    // `pminud`. A float lane answers false and nothing asks: `minps` is the only float ordering.
    bool isSignedLanes() const {
        auto kind = getMinMax();
        return kind == LowerMinMax::IMin || kind == LowerMinMax::IMax;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs;
};

// The widening multiply of the even 32-bit lanes - see LowerInst::X86MulWide, which states why this
// is the backend's own instruction and why its signedness is not the type's.
struct LowerInstX86MulWide: LowerInstSingle {
    LowerInstX86MulWide(StringId name, LowerType type, LowerPtr<LowerValue> lhs,
                        LowerPtr<LowerValue> rhs, bool signedLanes):
        LowerInstSingle(X86MulWide, name, type), lhs(lhs), rhs(rhs)
    {
        usedCount = 2;
        flags = signedLanes ? 1 : 0;
    }

    // Whether the 32-bit lanes are widened as signed, which is `pmuldq` against `pmuludq`.
    bool isSignedLanes() const { return flags != 0; }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs;
};

// The sign of a narrow value put back into the whole register - see LowerInst::X86Sext, which states
// why the width read is the instruction's own and not its operand type's.
struct LowerInstX86Sext: LowerInstSingle {
    LowerInstX86Sext(StringId name, LowerType type, LowerPtr<LowerValue> from, U8 sourceBytes):
        LowerInstSingle(X86Sext, name, type), from(from)
    {
        usedCount = 1;
        flags = sourceBytes;
    }

    // How many bytes of the operand are read: 1, 2 or 4. See LowerInst::X86Sext.
    U8 sourceBytes() const { return flags; }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

// `~lhs & rhs` - see LowerInst::X86AndNot, which states why the complemented operand is named by
// the instruction rather than left to an operand order.
struct LowerInstX86AndNot: LowerInstSingle {
    LowerInstX86AndNot(StringId name, LowerType type, LowerPtr<LowerValue> lhs, LowerPtr<LowerValue> rhs):
        LowerInstSingle(X86AndNot, name, type), lhs(lhs), rhs(rhs)
    {
        usedCount = 2;
    }

    // Used values must be first after embedded values. `lhs` is the complemented one.
    LowerPtr<LowerValue> lhs, rhs;
};

/*
 * Which of the three lowest-bit operations an `X86LowBit` performs - see the kind.
 *
 * Named for the answer rather than for the instruction, which is the naming `LowerMinMax` above
 * uses and the naming `Core.Bits` uses at the language end: `Clear` is `blsr`, `Isolate` is `blsi`
 * and `Mask` is `blsmsk`, and each name says what the result *is* rather than which three letters
 * encode it.
 */
enum class LowerX86LowBit: U8 {
    Clear,   // the operand with its lowest set bit cleared - `x & (x - 1)`
    Isolate, // the lowest set bit alone - `x & -x`
    Mask,    // every bit below the lowest set one, and that one - `x ^ (x - 1)`
};

// One of the three lowest-bit operations - see LowerInst::X86LowBit.
struct LowerInstX86LowBit: LowerInstSingle {
    LowerInstX86LowBit(StringId name, LowerType type, LowerPtr<LowerValue> from, LowerX86LowBit which):
        LowerInstSingle(X86LowBit, name, type), from(from)
    {
        usedCount = 1;
        flags = U8(which);
    }

    LowerX86LowBit getLowBit() const { return (LowerX86LowBit)flags; }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

// A vector permuted by a vector of lane indices - see LowerInst::X86Permute. The operand order is
// the machine's: `vpermd ymm1, ymm2, ymm3` reads the indices out of `ymm2`, which the encoding puts
// in `vvvv`, and the vector being permuted out of the r/m operand.
struct LowerInstX86Permute: LowerInstSingle {
    LowerInstX86Permute(StringId name, LowerType type, LowerPtr<LowerValue> indices,
                        LowerPtr<LowerValue> from):
        LowerInstSingle(X86Permute, name, type), indices(indices), from(from)
    {
        usedCount = 2;
    }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> indices, from;
};

// A vector masked by a mask of its own shape - see LowerInst::X86MaskAnd, which states why the
// operand order is the machine's and why the complemented form takes them the other way round.
struct LowerInstX86MaskAnd: LowerInstSingle {
    LowerInstX86MaskAnd(StringId name, LowerType type, LowerPtr<LowerValue> lhs,
                        LowerPtr<LowerValue> rhs, bool complemented):
        LowerInstSingle(X86MaskAnd, name, type), lhs(lhs), rhs(rhs)
    {
        usedCount = 2;
        flags = complemented ? 1 : 0;
    }

    // Whether the mask is the arm that is *dropped* rather than the one that is kept, which is
    // `pandn` against `pand`. The mask is then `lhs`, that being the operand `pandn` complements.
    bool isComplemented() const { return flags != 0; }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> lhs, rhs;
};

/*
 * Intrinsics.
 *
 * A machine operation the program asked for by name, rather than one the lowering derived from
 * something more abstract. The instructions above all mean something a target-independent optimizer
 * could reason about; an intrinsic means "emit this operation", and what it does to the machine is
 * the target's description of it rather than anything stated here.
 *
 * So this carries an identifier and its operands, and nothing else. Everything an intrinsic needs in
 * order to be allocated and emitted - which registers it forces its operands into, what it clobbers,
 * which of its results goes where, how it is encoded - is one row of the target's intrinsic registry
 * (see codegen/x64/intrinsic.cpp). Adding one is that row plus a name here.
 *
 * The identifiers are named centrally, the way LowerCallType names conventions the lower IR does not
 * itself implement: an intrinsic is meaningless without a target, but the IR still has to be able to
 * write one down, print it and parse it back.
 */
enum class LowerIntrinsic: U16 {
    // A byte reversal is *not* here, and the absence is the point: `bswap` is `LowerInst::Bswap`, an
    // ordinary unary this IR's own passes can fold, hoist and combine. An intrinsic is opaque to all
    // three - see the note on that kind, and §3.1.3 of codegen/x64/README.md for the memory forms
    // that opacity would also have cost.
    Popcnt,  // count the set bits of an integer

    /*
     * The number of zero bits below the lowest set bit of an integer, in two kinds that differ only
     * in what a zero operand answers - which is the one thing about this operation that is not the
     * same everywhere, and so is the one thing the IR has to say out loud.
     *
     * `Cttz` is **undefined at zero**, which is `llvm.cttz`'s poison zero and x86's `bsf`. An
     * emitter owes it a non-zero operand.
     *
     * `CttzWidth` **answers the operand's width at zero** - 32 for an `i32`, 64 for an `i64` - which
     * is `tzcnt` and needs the feature level that has it. It is not a convenience: a mask whose bits
     * fill their word has no bit above them to mark, so an operand that may be zero is the shape
     * rather than an oversight, and the width is exactly the answer wanted. See `expandMaskFirstSet`,
     * which spends the sentinel where one fits and this where none does.
     */
    Cttz,
    CttzWidth,

    /*
     * The other end of the word, in the same two kinds and for the same reason - and the pair is
     * *not* symmetric with the one above, which is x86's doing rather than a choice made here.
     *
     * `Bsr` answers the **index of the highest set bit**, not a count of anything: 31 for an `i32`
     * whose top bit is set, 0 for the value 1, and nothing at all for zero. That is `bsr`, it is
     * baseline, and the leading-zero count a caller wants is `width - 1 - Bsr(x)` - one subtraction
     * that the expansion below pays and the instruction above does not.
     *
     * `ClzWidth` answers the **leading-zero count** with the operand's width at zero, which is
     * `lzcnt` and needs LZCNT (v3, beside BMI1). It is what `Value::LeadingZeros` becomes, and
     * `expandBitScans` in the x64 backend is what turns it back into `Bsr` and a correction on a
     * target that has no such level.
     *
     * There is deliberately no poison-at-zero leading count to pair with `Cttz`: nothing produces
     * one. `Bsr` is here because the expansion needs a name for what it emits, and it is written
     * only by a backend that has the instruction - `LowerIntrinsic::Bzhi`'s case exactly, and
     * refused by the LLVM backend the same way.
     */
    Bsr,
    ClzWidth,

    /*
     * The low `index` bits of a value, with everything above them cleared - `bzhi`, BMI2.
     *
     * Two operands, the value and the bit count, in that order. **An index at or above the value's
     * width clears nothing**, which is the machine's rule and is stated here because a caller
     * relying on the other reading would be relying on nothing: the index is read from the low byte
     * of its operand, so a count of 256 is a count of zero and a negative one is a count of 255.
     * Whoever emits this owes it an index it has narrowed itself.
     *
     * Written only by a backend that has the instruction, for the reason `LowerReduce::Bits` is:
     * without it this is three general-register instructions and a constant, and a target with a
     * different answer should write its own rather than expand somebody else's.
     */
    Bzhi,

    /*
     * The two directions of an arbitrary bit permutation - `pext` and `pdep`, BMI2.
     *
     * `Pext` packs the bits of its first operand at the set positions of its second down into a
     * contiguous low field; `Pdep` spreads a low field back out into those positions. Both are total
     * and neither has a rule the machine and the IR disagree about, which is the difference from
     * `Bzhi` above: a permutation has no count for a byte to truncate.
     *
     * Written only by a backend that has the instructions, on `Bzhi`'s terms and refused by the LLVM
     * backend the same way. `LowerInst::GatherBits` and `LowerInst::ScatterBits` are what every tier
     * above a backend carries instead, and `expandBitOperations` in the x64 backend is what turns
     * one into the other where the feature is present - and into the parallel-suffix network where
     * it is not.
     *
     * **A caution that belongs with the instruction rather than with any caller**: these two are
     * microcoded on AMD's Zen 1 and Zen 2, at tens of cycles against the three a Zen 3 or an Intel
     * part takes. A build that names a feature level gets what it asked for; nothing here tries to
     * detect a vendor.
     */
    Pext,
    Pdep,
    Cpuid,   // query the processor's feature information
    Rdtscp,  // read the processor's timestamp counter and its id
    Rdtsc,   // read the processor's timestamp counter

    // Memory ordering. Neither reads nor writes anything itself; each one constrains where the
    // accesses around it may be moved to, which is why the IR has to be able to name them at all.
    MFence,
    LFence,
    SFence,
    Pause,   // a hint that this is a spin loop, not a barrier - see the registry

    // Cache and translation control. Each takes the address it operates on, and only that.
    Prefetch,     // fetch a line towards the processor, with no architectural effect
    PrefetchNta,  // the same, without displacing what the caches already hold
    Clflush,      // write a line back and evict it, everywhere it is held
    Invlpg,       // drop the translation of one page

    // Interrupts and processor state. The four below take nothing and answer nothing: what they do
    // is to the processor rather than to any value.
    Hlt,
    Cli,
    Sti,
    Swapgs,

    // Model-specific and extended-state registers.
    Rdmsr,
    Wrmsr,
    Xgetbv,

    // Port I/O, at the two widths a port is addressed at. The port number is a value rather than a
    // constant here; see the registry for why that is not the shorter encoding's fault.
    In8,
    In32,
    Out8,
    Out32,

    // Control registers. One intrinsic per register rather than one taking a number, because the
    // number is part of the encoding rather than an operand of it.
    ReadCr0,
    ReadCr2,
    ReadCr3,
    ReadCr4,
    WriteCr0,
    WriteCr3,
    WriteCr4,

    LastIntrinsic = WriteCr4,
};

static constexpr Size kLowerIntrinsicCount = Size(LowerIntrinsic::LastIntrinsic) + 1;

// What the IR itself knows about an intrinsic: how it is written, and how many values go in and come
// out. The arity is here rather than in the target registry because it is what the parser and the
// validator check, and both run before any target has been chosen.
struct LowerIntrinsicDesc {
    StringView name;
    U8 results;
    U8 args;
};

const LowerIntrinsicDesc& lowerIntrinsicDesc(LowerIntrinsic id);

// Looks an intrinsic up by the name it is written as, hashed as every identifier is. Nothing if
// there is no such intrinsic. This is what makes the table in lower.cpp the one statement of which
// intrinsics exist: the parser registers a handler per name from it and recovers the identifier
// through here, so adding a row makes an intrinsic writable with no line of its own anywhere.
Maybe<LowerIntrinsic> findLowerIntrinsic(StringId name);

struct LowerInstIntrinsic: LowerInst {
    LowerInstIntrinsic(LowerIntrinsic intrinsic, Size createdCount, Size usedCount):
        LowerInst(Intrinsic), intrinsic(intrinsic)
    {
        this->createdCount = createdCount;
        this->usedCount = usedCount;
    }

    LowerIntrinsic getIntrinsic() const { return intrinsic; }

    // LowerInst::used contains the operand list and LowerInst::created the results, both in the
    // order the intrinsic's description states.
    LowerIntrinsic intrinsic;
};

/*
 * `movbe r, [address]` and `movbe [address], r` - see LowerInst::X86MovbeLoad.
 *
 * Written exactly as the `Load` and `Store` they were folded out of, one field lighter: there is no
 * sign to extend, a reversal being defined only where the value is the whole of its register.
 */
struct LowerInstX86MovbeLoad: LowerInstSingle {
    LowerInstX86MovbeLoad(LowerPtr<LowerValue> from, StringId name, LowerType type, U32 width):
        LowerInstSingle(X86MovbeLoad, name, type), from(from)
    {
        usedCount = 1;
        flags = makeMemoryFlags(width, false);
    }

    U32 getWidth() const { return getMemoryWidth(flags); }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> from;
};

struct LowerInstX86MovbeStore: LowerInst {
    LowerInstX86MovbeStore(LowerPtr<LowerValue> to, LowerPtr<LowerValue> value, U32 width):
        LowerInst(X86MovbeStore), to(to), value(value)
    {
        usedCount = 2;
        flags = makeMemoryFlags(width, false);
    }

    U32 getWidth() const { return getMemoryWidth(flags); }

    // Used values must be first after embedded values.
    LowerPtr<LowerValue> to, value;
};

struct LowerInstCall: LowerInst {
    explicit LowerInstCall(Size createdCount, Size usedCount, LowerCallType callType): LowerInst(Call) {
        this->createdCount = createdCount;
        this->usedCount = usedCount;
        this->flags = (U8)callType;
    }

    LowerCallType getCallType() const {
        return (LowerCallType)flags;
    }

    // LowerInst::used contains the argument list. The first value is the called function.
    // LowerInst::created contains the returned values.
};

/*
 * Control flow.
 */

// Conditional branch to one of two blocks.
// Can only exist in the terminator field of a block.
struct LowerInstJe: LowerInst {
    LowerInstJe(LowerPtr<LowerValue> cond, LowerPtr<LowerBlock> then, LowerPtr<LowerBlock> otherwise):
        LowerInst(Je), then(then), otherwise(otherwise), cond(cond)
    {
        usedCount = 1;
    }

    // Set if the comparison uses retained flags, rather than a register-stored comparison.
    // In this case, `cond` is only used implicitly.
    Maybe<LowerCmp> getEmbeddedCmp() const {
        return decodeOptionalCmp(flags);
    }

    void setEmbeddedCmp(Maybe<LowerCmp> cmp) {
        flags = encodeOptionalCmp(cmp);
    }

    // Whether either edge carries a claim about how likely it is, as against both being unknown.
    bool hasLikelihood() const {
        return likelihood[0].source != LikelihoodSource::Unknown
            || likelihood[1].source != LikelihoodSource::Unknown;
    }

    LowerPtr<LowerValue> cond;
    LowerPtr<LowerBlock> then;
    LowerPtr<LowerBlock> otherwise;

    // How likely each edge is relative to the other - see EdgeLikelihood. Index 0 is `then` and
    // index 1 is `otherwise`, which is also the order the containing block lists them in
    // `outgoing`, so the two are indexed alike everywhere.
    //
    // Indexed by edge rather than named per target block, which is what makes the metadata survive
    // a CFG transform for free: splitting an edge retargets `then` or `otherwise` in place, and the
    // weight of edge 0 is still the weight of edge 0 when it now leads to the split block instead.
    // The inserted block's own jump has one successor and so needs no weight at all.
    EdgeLikelihood likelihood[2];
};

// Unconditional branch to a different block.
// Can only exist in the terminator field of a block.
struct LowerInstJmp: LowerInst {
    LowerInstJmp(LowerPtr<LowerBlock> then): LowerInst(Jmp), then(then) {}

    LowerPtr<LowerBlock> then;
};

// Return the provided value to the parent function.
// Can only exist in the terminator field of a block.
struct LowerInstRet: LowerInst {
    explicit LowerInstRet(): LowerInst(Ret) {}

    // LowerInst::usedValues contains the returned values list.
    // The list can be empty if the function returns nothing.
};

/*
 * The end of a block nothing arrives at the end of.
 *
 * No operands and no successors, which is what makes every walk in the backend already correct about
 * it: liveness ends here because nothing is live out of a block with no edges, and the frame is
 * never restored because control does not leave. The x64 form encodes zero bytes - see FormNoReturn,
 * which is the only form in the table that emits nothing and is allowed to.
 */
struct LowerInstUnreachable: LowerInst {
    explicit LowerInstUnreachable(): LowerInst(Unreachable) {}
};

// SSA ϕ-node. Can only exist in the list of phi nodes of a block.
struct LowerInstPhi: LowerInstSingle {
    LowerInstPhi(StringId name, LowerType type): LowerInstSingle(Phi, name, type) {}

    // Returns a list of source blocks where each block corresponds to a value in LowerInst::used().
    Buffer<LowerPtr<LowerBlock>> sources() {
        auto u = used();
        return { (LowerPtr<LowerBlock>*)(u.ptr + u.length), u.length };
    }

    // LowerInst::used contains the values to pick from.
    // The list of corresponding blocks is located past the used values list.
};

inline LiveSet* Liveness::getBlock(LowerBlock* b) {
    return &blockMap[b->index];
}

inline LowerValue* Liveness::getValue(LiveId id) {
    assertTrue(id < kNullLive);
    return valueMap[id];
}

inline LiveId LowerValue::liveId() {
    auto i = inst();
    auto first = i->liveId;
    if(first == kNullLive) return kNullLive;

    return first + (this - i->created().ptr);
}
